# Generated by Django 3.1.1 on 2020-09-14 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200908_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 13, 3, 10, 973371, tzinfo=utc)),
        ),
    ]
