# Generated by Django 3.1.1 on 2020-09-15 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200914_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 4, 35, 53, 849916, tzinfo=utc)),
        ),
    ]
