# Generated by Django 3.1.1 on 2020-09-22 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200915_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 0, 43, 50, 738265, tzinfo=utc)),
        ),
    ]
